theme: minima
title: Let's Get This Bread
author: kavanase
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is just a website I have made while learning to use GitHub pages. 
  To be honest, there's not much to see here really...

# social links
twitter_username: Kavanagh_Sean_
github_username:  kavanase

show_excerpts: true # set to false to remove excerpts on the homepage
